name: â™ˆ Daily Rashifal Auto Update

on:
  schedule:
    - cron: '0 23 * * *' # à¤°à¥‹à¤œà¤¼ 4:30 AM IST (23:00 UTC)
  workflow_dispatch: # manually run à¤­à¥€ à¤•à¤° à¤¸à¤•à¤¤à¥‡ à¤¹à¥ˆà¤‚

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Daily Rashifal JSON
        run: |
          DATE=$(date +%F)
          cat > rashifal.json <<EOL
          {
            "date": "$DATE",
            "à¤®à¥‡à¤·": "à¤†à¤œ à¤†à¤ªà¤•à¤¾ à¤†à¤¤à¥à¤®à¤µà¤¿à¤¶à¥à¤µà¤¾à¤¸ à¤¬à¤¢à¤¼à¥‡à¤—à¤¾à¥¤ à¤•à¤¾à¤°à¥à¤¯ à¤®à¥‡à¤‚ à¤¨à¤ˆ à¤‰à¤ªà¤²à¤¬à¥à¤§à¤¿à¤¯à¤¾à¤ à¤®à¤¿à¤²à¥‡à¤‚à¤—à¥€à¥¤",
            "à¤µà¥ƒà¤·à¤­": "à¤ªà¤°à¤¿à¤µà¤¾à¤° à¤•à¥‡ à¤¸à¤¾à¤¥ à¤¸à¤®à¤¯ à¤¬à¤¿à¤¤à¤¾à¤¨à¥‡ à¤•à¤¾ à¤…à¤µà¤¸à¤° à¤®à¤¿à¤²à¥‡à¤—à¤¾à¥¤ à¤†à¤°à¥à¤¥à¤¿à¤• à¤²à¤¾à¤­ à¤¹à¥‹à¤—à¤¾à¥¤",
            "à¤®à¤¿à¤¥à¥à¤¨": "à¤ªà¥à¤°à¤¾à¤¨à¥‡ à¤•à¤¾à¤® à¤ªà¥‚à¤°à¥‡ à¤¹à¥‹à¤‚à¤—à¥‡à¥¤ à¤¯à¤¾à¤¤à¥à¤°à¤¾ à¤•à¤¾ à¤¯à¥‹à¤— à¤¹à¥ˆà¥¤",
            "à¤•à¤°à¥à¤•": "à¤¸à¥à¤µà¤¾à¤¸à¥à¤¥à¥à¤¯ à¤•à¤¾ à¤§à¥à¤¯à¤¾à¤¨ à¤°à¤–à¥‡à¤‚à¥¤ à¤ªà¤¾à¤°à¤¿à¤µà¤¾à¤°à¤¿à¤• à¤•à¤¾à¤°à¥à¤¯à¥‹à¤‚ à¤®à¥‡à¤‚ à¤µà¥à¤¯à¤¸à¥à¤¤ à¤°à¤¹à¥‡à¤‚à¤—à¥‡à¥¤",
            "à¤¸à¤¿à¤‚à¤¹": "à¤¨à¥Œà¤•à¤°à¥€ à¤”à¤° à¤µà¥à¤¯à¤¾à¤ªà¤¾à¤° à¤®à¥‡à¤‚ à¤¤à¤°à¤•à¥à¤•à¥€ à¤•à¥‡ à¤¯à¥‹à¤— à¤¹à¥ˆà¤‚à¥¤",
            "à¤•à¤¨à¥à¤¯à¤¾": "à¤†à¤œ à¤•à¤¿à¤¸à¥€ à¤¶à¥à¤­ à¤¸à¤®à¤¾à¤šà¤¾à¤° à¤•à¥€ à¤ªà¥à¤°à¤¾à¤ªà¥à¤¤à¤¿ à¤¹à¥‹à¤—à¥€à¥¤",
            "à¤¤à¥à¤²à¤¾": "à¤°à¤¿à¤¶à¥à¤¤à¥‹à¤‚ à¤®à¥‡à¤‚ à¤®à¤§à¥à¤°à¤¤à¤¾ à¤†à¤à¤—à¥€à¥¤ à¤¨à¤ à¤®à¤¿à¤¤à¥à¤° à¤¬à¤¨à¥‡à¤‚à¤—à¥‡à¥¤",
            "à¤µà¥ƒà¤¶à¥à¤šà¤¿à¤•": "à¤—à¥‹à¤ªà¤¨à¥€à¤¯ à¤¬à¤¾à¤¤à¥‹à¤‚ à¤•à¥‹ à¤¸à¤¾à¤à¤¾ à¤•à¤°à¤¨à¥‡ à¤¸à¥‡ à¤¬à¤šà¥‡à¤‚à¥¤ à¤¸à¤‚à¤¯à¤® à¤°à¤–à¥‡à¤‚à¥¤",
            "à¤§à¤¨à¥": "à¤®à¤¾à¤¨-à¤¸à¤®à¥à¤®à¤¾à¤¨ à¤”à¤° à¤²à¤¾à¤­ à¤•à¥‡ à¤¯à¥‹à¤— à¤¹à¥ˆà¤‚à¥¤",
            "à¤®à¤•à¤°": "à¤¨à¤ˆ à¤œà¤¿à¤®à¥à¤®à¥‡à¤¦à¤¾à¤°à¥€ à¤®à¤¿à¤²à¥‡à¤—à¥€à¥¤ à¤®à¥‡à¤¹à¤¨à¤¤ à¤•à¤¾ à¤«à¤² à¤®à¤¿à¤²à¥‡à¤—à¤¾à¥¤",
            "à¤•à¥à¤‚à¤­": "à¤¯à¥‹à¤œà¤¨à¤¾ à¤…à¤¨à¥à¤¸à¤¾à¤° à¤•à¤¾à¤°à¥à¤¯ à¤ªà¥‚à¤°à¥‡ à¤¹à¥‹à¤‚à¤—à¥‡à¥¤ à¤®à¤¿à¤¤à¥à¤°à¥‹à¤‚ à¤•à¤¾ à¤¸à¤¹à¤¯à¥‹à¤— à¤®à¤¿à¤²à¥‡à¤—à¤¾à¥¤",
            "à¤®à¥€à¤¨": "à¤§à¤¾à¤°à¥à¤®à¤¿à¤• à¤•à¤¾à¤°à¥à¤¯à¥‹à¤‚ à¤®à¥‡à¤‚ à¤®à¤¨ à¤²à¤—à¥‡à¤—à¤¾à¥¤ à¤ªà¤°à¤¿à¤µà¤¾à¤° à¤®à¥‡à¤‚ à¤¶à¤¾à¤‚à¤¤à¤¿ à¤°à¤¹à¥‡à¤—à¥€à¥¤"
          }
          EOL

      - name: Commit and Push
        run: |
          git config --global user.name "Rashifal Bot"
          git config --global user.email "bot@users.noreply.github.com"
          git add rashifal.json
          git commit -m "ðŸ”® Auto update Rashifal for $(date +%F)" || echo "No changes to commit"
          git push
