name: â™»ï¸ Auto Update Rashifal

on:
  schedule:
    - cron: '0 0 * * *' # â° à¤°à¥‹à¤œà¤¼ à¤†à¤§à¥€ à¤°à¤¾à¤¤ (UTC) à¤•à¥‹ à¤šà¤²à¥‡à¤—à¤¾ (à¤­à¤¾à¤°à¤¤ à¤®à¥‡à¤‚ à¤¸à¥à¤¬à¤¹ 5:30 à¤¬à¤œà¥‡)
  workflow_dispatch: # Manual run option

jobs:
  update-rashifal:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ§­ Checkout Repository
        uses: actions/checkout@v3

      - name: ðŸª Generate Daily Rashifal JSON
        run: |
          # à¤†à¤œ à¤•à¥€ à¤¤à¤¾à¤°à¥€à¤–
          DATE=$(date +%Y-%m-%d)

          cat > rashifal.json <<EOF
          {
            "date": "$DATE",
            "rashifal": {
              "à¤®à¥‡à¤·": "à¤†à¤œ à¤†à¤¤à¥à¤®à¤µà¤¿à¤¶à¥à¤µà¤¾à¤¸ à¤Šà¤à¤šà¤¾ à¤°à¤¹à¥‡à¤—à¤¾à¥¤ à¤•à¤¾à¤°à¥à¤¯ à¤®à¥‡à¤‚ à¤¸à¤«à¤²à¤¤à¤¾ à¤®à¤¿à¤²à¥‡à¤—à¥€à¥¤",
              "à¤µà¥ƒà¤·à¤­": "à¤ªà¤°à¤¿à¤µà¤¾à¤° à¤•à¥‡ à¤¸à¤¾à¤¥ à¤…à¤šà¥à¤›à¤¾ à¤¸à¤®à¤¯ à¤¬à¥€à¤¤à¥‡à¤—à¤¾à¥¤ à¤§à¤¨ à¤²à¤¾à¤­ à¤•à¥‡ à¤¯à¥‹à¤— à¤¹à¥ˆà¤‚à¥¤",
              "à¤®à¤¿à¤¥à¥à¤¨": "à¤ªà¥à¤°à¤¾à¤¨à¥‡ à¤•à¤¾à¤°à¥à¤¯ à¤ªà¥‚à¤°à¥‡ à¤¹à¥‹à¤‚à¤—à¥‡à¥¤ à¤¯à¤¾à¤¤à¥à¤°à¤¾ à¤¸à¤‚à¤­à¤µ à¤¹à¥ˆà¥¤",
              "à¤•à¤°à¥à¤•": "à¤¸à¥à¤µà¤¾à¤¸à¥à¤¥à¥à¤¯ à¤•à¤¾ à¤§à¥à¤¯à¤¾à¤¨ à¤°à¤–à¥‡à¤‚à¥¤ à¤¨à¤ à¤…à¤µà¤¸à¤° à¤ªà¥à¤°à¤¾à¤ªà¥à¤¤ à¤¹à¥‹à¤‚à¤—à¥‡à¥¤",
              "à¤¸à¤¿à¤‚à¤¹": "à¤¸à¤®à¥à¤®à¤¾à¤¨ à¤µ à¤¯à¤¶ à¤•à¥€ à¤ªà¥à¤°à¤¾à¤ªà¥à¤¤à¤¿ à¤¹à¥‹à¤—à¥€à¥¤ à¤‰à¤¤à¥à¤¸à¤¾à¤¹ à¤¬à¤¨à¤¾ à¤°à¤¹à¥‡à¤—à¤¾à¥¤",
              "à¤•à¤¨à¥à¤¯à¤¾": "à¤•à¤¿à¤¸à¥€ à¤¬à¤¡à¤¼à¥‡ à¤•à¤¾à¤°à¥à¤¯ à¤®à¥‡à¤‚ à¤¸à¤«à¤²à¤¤à¤¾ à¤®à¤¿à¤²à¥‡à¤—à¥€à¥¤ à¤ªà¤°à¤¿à¤µà¤¾à¤° à¤®à¥‡à¤‚ à¤†à¤¨à¤‚à¤¦ à¤°à¤¹à¥‡à¤—à¤¾à¥¤",
              "à¤¤à¥à¤²à¤¾": "à¤ªà¥à¤°à¥‡à¤® à¤¸à¤‚à¤¬à¤‚à¤§à¥‹à¤‚ à¤®à¥‡à¤‚ à¤ªà¥à¤°à¤—à¤¾à¤¢à¤¼à¤¤à¤¾ à¤†à¤à¤—à¥€à¥¤ à¤¶à¥à¤­ à¤¸à¤®à¤¾à¤šà¤¾à¤° à¤®à¤¿à¤²à¥‡à¤‚à¤—à¥‡à¥¤",
              "à¤µà¥ƒà¤¶à¥à¤šà¤¿à¤•": "à¤—à¥à¤ªà¥à¤¤ à¤¶à¤¤à¥à¤°à¥à¤“à¤‚ à¤¸à¥‡ à¤¸à¤¾à¤µà¤§à¤¾à¤¨ à¤°à¤¹à¥‡à¤‚à¥¤ à¤–à¤°à¥à¤š à¤¨à¤¿à¤¯à¤‚à¤¤à¥à¤°à¤¿à¤¤ à¤°à¤–à¥‡à¤‚à¥¤",
              "à¤§à¤¨à¥": "à¤µà¤¿à¤¦à¥à¤¯à¤¾à¤°à¥à¤¥à¤¿à¤¯à¥‹à¤‚ à¤•à¥‡ à¤²à¤¿à¤ à¤¦à¤¿à¤¨ à¤¶à¥à¤­ à¤°à¤¹à¥‡à¤—à¤¾à¥¤ à¤®à¤¾à¤¨-à¤¸à¤®à¥à¤®à¤¾à¤¨ à¤¬à¤¢à¤¼à¥‡à¤—à¤¾à¥¤",
              "à¤®à¤•à¤°": "à¤¨à¤ˆ à¤œà¤¿à¤®à¥à¤®à¥‡à¤¦à¤¾à¤°à¥€ à¤®à¤¿à¤² à¤¸à¤•à¤¤à¥€ à¤¹à¥ˆà¥¤ à¤®à¥‡à¤¹à¤¨à¤¤ à¤•à¤¾ à¤«à¤² à¤®à¤¿à¤²à¥‡à¤—à¤¾à¥¤",
              "à¤•à¥à¤‚à¤­": "à¤¨à¤ à¤²à¥‹à¤—à¥‹à¤‚ à¤¸à¥‡ à¤¸à¤‚à¤ªà¤°à¥à¤• à¤²à¤¾à¤­à¤¦à¤¾à¤¯à¤• à¤°à¤¹à¥‡à¤—à¤¾à¥¤ à¤®à¤¨ à¤ªà¥à¤°à¤¸à¤¨à¥à¤¨ à¤°à¤¹à¥‡à¤—à¤¾à¥¤",
              "à¤®à¥€à¤¨": "à¤ªà¤°à¤¿à¤µà¤¾à¤° à¤®à¥‡à¤‚ à¤¸à¤¾à¤®à¤‚à¤œà¤¸à¥à¤¯ à¤°à¤¹à¥‡à¤—à¤¾à¥¤ à¤§à¤¾à¤°à¥à¤®à¤¿à¤• à¤•à¤¾à¤°à¥à¤¯à¥‹à¤‚ à¤®à¥‡à¤‚ à¤®à¤¨ à¤²à¤—à¥‡à¤—à¤¾à¥¤"
            }
          }
          EOF

      - name: âœ… Commit and Push Updated Rashifal
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add rashifal.json
          git commit -m "ðŸ”® Auto update rashifal: $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push
